### ISSUE TITLE
Spring Session: Activate Spring Session auto-configuration support solely by adding the dependency

### ISSUE THREAD

**Issue by ghillert** [coherence-community/coherence-spring#61]
When user a user adds the Coherence Spring Session dependency, Spring Boot's auto-configuration support should be activated by default.

Right now, Spring session support needs to be manually enabled via: 

```
coherence:
  spring:
    session:
      enabled: true
```
